<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="C:\rustservers\server/Carbon.targets" />
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="Carbon.Hooks.Oxide">
			<HintPath>..\..\..\server\carbon\managed\hooks\Carbon.Hooks.Oxide.dll</HintPath>
		</Reference>
		<Reference Include="Oxide.Ext.Discord">
			<HintPath>C:\rustservers\server\carbon\extensions\Oxide.Ext.Discord.dll</HintPath>
		</Reference>
		<Reference Include="Oxide.Core">
			<HintPath>C:\rustservers\server\carbon\managed\Oxide.Core.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>
